# Generated by Django 2.1.3 on 2018-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('planet', models.CharField(max_length=255)),
                ('discovered', models.DateField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
